name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.1.1
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.3
  path_provider_windows: ^2.0.4
  signature: ^5.0.0
  path: ^1.9.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  docx_template: ^0.4.0
  uuid: ^4.4.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  reflectable: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  objectbox_generator: any

flutter:
  uses-material-design: true


  assets:
    - assets/Form.png
    - assets/AvecH.png
    - assets/Scout.png
    - assets/Logo.jpg
    - assets/Gif1.gif
    - assets/Gif2.gif
    - assets/docx/

